language: php

php:
  - 5.6
  - 7.0
  - 7.1

script:
  - php composer.phar self-update
  - php composer.phar install --dev
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml --testsuite all

addons:
    code_climate:
        repo_token: 0f5ce023260e7df34832da09aba27723bcc7244ccefb87bbff4fe9d3704c68d3

after_success:
  - vendor/bin/test-reporter