language: php

php:
  - 5.6
  - 7.0
  - 7.1

script:
  - php composer.phar self-update
  - php composer.phar install --dev
  - ./vendor/bin/phpunit --testsuite unit
  - ./vendor/bin/phpunit --testsuite integration
